sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: mcxiaodandan153+
  alioss:
    access-key-id: LTAI5tDgZ1GuaFAwSA1n5kPq
    access-key-secret: GsgKvi70eqEPIvhoboCsvmAMcjMF1B
    bucket-name: lovesana
    endpoint: oss-cn-beijing.aliyuncs.com
  wechat:
    appid: wxf26a969cc9e71657
    secret: 490ae63cc62353e307840fc2a142bbff
